[package]
name = "er_mule_copier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
dioxus = {git = "https://github.com/DioxusLabs/dioxus.git", branch="master"}
dioxus-desktop = {git = "https://github.com/DioxusLabs/dioxus.git", branch="master"}
gumdrop = "0.8.1"
md5 = "0.7.0"
text_io = "0.1.12"
rfd = { version = "0.11.2", default-features = false,  features = ["xdg-portal"]}