[package]
name = "er_mule_copier"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli"

[[bin]]
name = "gui"


[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
comfy-table = "6.1.4"
dirs-next = "2.0.0"
md5 = "0.7.0"
text_io = "0.1.12"
