[package]
name = "er_mule_copier"
version = "0.1.0"
edition = "2021"
description = "Copy character slots in Elden Ring"
authors = ["https://github.com/pubnoconst"]
license = "MIT"

[package.metadata.bundle]
name = "er_mule_copier"
identifier = "com.github.pubnoconst.er_mule_copier"
version = "0.1.0"
short_description = "Copy character slots in Elden Ring"
deb_depends = ["rust-1.62-all", "libwebkitgtk-3.0-dev"]
long_description = """
This app copies characters into your save file in Elden Ring
"""


[dependencies]
cli-table = "0.4.7"
dioxus = {git = "https://github.com/DioxusLabs/dioxus.git", rev="972cd25"}
dioxus-desktop = {git = "https://github.com/DioxusLabs/dioxus.git", rev="972cd25"}
gumdrop = "0.8.1"
md5 = "0.7.0"
text_io = "0.1.12"
rfd = { version = "0.11.2", default-features = false,  features = ["xdg-portal"]}